# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_remove_place_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='place',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='place',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='place',
            name='house_rules',
        ),
        migrations.RemoveField(
            model_name='place',
            name='times_viewed',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='place',
            name='streetName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='streetNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(max_length=25),
        ),
    ]
